site_name: Documentação
repo_name: "2024.2-Champions"
repo_url: https://github.com/FGA-REQ/2024.2-Champions
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/2024.2-Champions
    footer:
      copyright: "© 2025 MediaMestre"
nav:
  - Página Inicial: "index.md"
  - Histórico de Versões: "historico/historico.md"
  - Regras de Negócio: "regras-negocio.md"
  - Declaração de Requisitos:
      - Visão do Produto e do Projeto: 'visao-produto-projeto.md'
      - Histórias de Usuário: "dec/historias-usuario.md"
      - Fluxo de Usuário: "dec/fluxo-usuario.md"
      - Declaração: "dec/declaracao-requisitos.md"
      - Backlog do Produto: "dec/backlog.md"

extra_css:
  - css/extra.css
